name: Test PR when ready for review

on:
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      
      - name: Install dependencies
        run: bun install
      
      - name: Install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          ./install.sh /usr/local
      
      - name: Run unit tests
        run: bun test
      
      - name: Run CLI tests
        run: bats bats/*.bats
