name: Test PR when ready for review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Setup mise
        uses: jdx/mise-action@v2
      
      - name: Install dependencies
        run: |
          mise install
          bun install
      
      - name: Run unit tests
        run: bun test
      
      - name: Run CLI tests
        run: bats bats/*.bats
